[build]
target="wasm32-wasip1-threads"
# target="x86_64-pc-windows-gnu"

# this does not appear to work no matter what I try
# [target.'cfg(feature = "wasmedge")']
# runner = "wasmedge"

[target.'cfg(feature = wamr)']
runner = "iwasm  --addr-pool=0.0.0.0/0"

# [target.wasm32-wasip1]
# runner = "iwasm  --addr-pool=0.0.0.0/0"

# [target.'cfg(feature = "wasmedge")']
# runner = "wasmedge"

# [target.'cfg(any(feature = "wamr"), not(feature = "wamr"))']
# runner = "iwasm  --addr-pool=0.0.0.0/0"

# [target.wasm32-wasip2]
# runner = "iwasm  --addr-pool=0.0.0.0/0"

# [target.wasm32-wasip1-threads]
# runner = "iwasm  --addr-pool=0.0.0.0/0"

# [target.wasm32-wasip3]
# runner = "iwasm  --addr-pool=0.0.0.0/0"

