[build]
# target="wasm32-wasip1"
target="wasm32-wasip1-threads"
# target="x86_64-pc-windows-gnu"
# target="x86_64-unknown-linux-gnu"

[target.wasm32-wasip1]
runner = "wasmedge"

[target.wasm32-wasip1-threads]
runner = "iwasm --addr-pool=0.0.0.0/0"

